.DEFAULT_GOAL := swagger

install_swagger:
# <TAB>go get -u github.com/go-swagger/go-swagger/cmd/swagger
	go get -u github.com/go-swagger/go-swagger/cmd/swagger

swagger:
# <TAB>@echo Ensure you have the swagger CLI or this command will fail.
# <TAB>@echo You can install the swagger CLI with: go get -u github.com/go-swagger/go-swagger/cmd/swagger
# <TAB>@echo ....
# <TAB>swagger generate spec -o ./swagger.yaml --scan-models
	@echo Ensure you have the swagger CLI or this command will fail.
	@echo You can install the swagger CLI with: go get -u github.com/go-swagger/go-swagger/cmd/swagger
	@echo ....
	swagger generate spec -o ./swagger.yaml --scan-models
	@echo Successfully Genertaed